"""Scanner domain models and data transfer contracts."""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


class CheckStatus(str, Enum):
    """Execution status of a security check."""

    PASS = "PASS"
    FAIL = "FAIL"
    MANUAL = "MANUAL"
    ERROR = "ERROR"


class SeverityLevel(str, Enum):
    """Standard security severity classification."""

    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class FindingStatus(str, Enum):
    """Status lifecycle of an identified security finding."""

    OPEN = "OPEN"
    CONFIRMED = "CONFIRMED"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    REMEDIATED = "REMEDIATED"
    MANUAL_VERIFICATION = "MANUAL_VERIFICATION"
    ENVIRONMENT_OBSERVATION = "ENVIRONMENT_OBSERVATION"
    SOURCE_REVIEW = "SOURCE_REVIEW"
    INFORMATIONAL = "INFORMATIONAL"


class EvidenceType(str, Enum):
    """Categorization of collected technical evidence."""

    HTTP_RESPONSE = "HTTP_RESPONSE"
    HTTP_HEADER = "HTTP_HEADER"
    SOURCE_CODE = "SOURCE_CODE"
    CONFIGURATION = "CONFIGURATION"
    DEPENDENCY = "DEPENDENCY"
    POC_RESULT = "POC_RESULT"
    SCREENSHOT = "SCREENSHOT"
    MANUAL = "MANUAL"


@dataclass
class EvidenceItem:
    """Technical evidence supporting a security check or finding."""

    evidence_type: str
    title: str
    description: Optional[str] = None
    request_data: Optional[str] = None
    response_data: Optional[str] = None
    source_file: Optional[str] = None
    source_line: Optional[int] = None
    redacted: bool = True


@dataclass
class FindingItem:
    """Security finding record generated by an assessment check."""

    finding_code: str
    title: str
    category: str
    severity: str
    status: str = FindingStatus.MANUAL_VERIFICATION.value
    confidence: Optional[float] = None
    cvss_score: Optional[float] = None
    cvss_vector: Optional[str] = None
    description: Optional[str] = None
    affected_component: Optional[str] = None
    impact: Optional[str] = None
    reproduction_steps: Optional[str] = None
    remediation: Optional[str] = None


@dataclass
class CheckResult:
    """Standardized output contract returned by every security check."""

    check_id: str
    category: str
    title: str
    status: str  # PASS, FAIL, MANUAL, ERROR
    severity: Optional[str] = None  # INFO, LOW, MEDIUM, HIGH, CRITICAL
    confidence: Optional[float] = 100.0  # 0 to 100
    description: str = ""
    affected_component: str = ""
    evidence: list[EvidenceItem] = field(default_factory=list)
    findings: list[FindingItem] = field(default_factory=list)
    recommendation: Optional[str] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
